[package]
authors = ["Kaikalii <kaikaliischmidt@gmail.com>"]
edition = '2021'
name = 'print_game'
version = '0.1.0'

[dependencies]
clap.features = ['derive']
clap.version = '4'
csscolorparser = '0.6.2'
ctrlc = '3.2.4'
eframe = '0.20.1'
once_cell = "1.17.0"

[workspace]
members = ['example']
