[package]
edition = '2021'
name = 'print_game'
version = '0.1.0'

[dependencies]
clap.features = ['derive']
clap.version = '4'
csscolorparser = "0.6.2"
eframe = '0.20.1'

[workspace]
members = ['example']
